services:
  - type: web
    name: coffee-perk-bot
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
